[srv]
srv ansible_host=158.160.47.93 ansible_user=ubuntu
[k8s-master]
k8s-master ansible_host=158.160.36.127 ansible_user=ubuntu
[k8s-app]
k8s-app ansible_host=158.160.49.45 ansible_user=ubuntu

[k8s:children]
k8s-master
k8s-app

