version: '3.8'

services:
  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    #это какая-то магия прав
    user: "0:0"
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/tmp/loki
    ports:
      - "3100:3100"
    restart: always
    networks:
      - monitoring-network

volumes:
  loki-data:

networks:
  monitoring-network:
    name: monitoring-network
